Name:           ros-indigo-laser-filters
Version:        1.8.3
Release:        0%{?dist}
Summary:        ROS laser_filters package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/laser_filters
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-angles
Requires:       ros-indigo-filters
Requires:       ros-indigo-laser-geometry
Requires:       ros-indigo-message-filters
Requires:       ros-indigo-pluginlib
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-tf
BuildRequires:  ros-indigo-angles
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-filters
BuildRequires:  ros-indigo-laser-geometry
BuildRequires:  ros-indigo-message-filters
BuildRequires:  ros-indigo-pluginlib
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-rostest
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-tf

%description
Assorted filters designed to operate on 2D planar laser scanners, which use the
sensor_msgs/LaserScan type.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri May 20 2016 Jon Binney <jon.binney@gmail.com> - 1.8.3-0
- Autogenerated by Bloom

* Sat Mar 26 2016 Jon Binney <jon.binney@gmail.com> - 1.8.1-0
- Autogenerated by Bloom

* Thu Dec 17 2015 Jon Binney <jbinney@willowgarage.com> - 1.7.4-1
- Autogenerated by Bloom

* Thu Dec 17 2015 Jon Binney <jbinney@willowgarage.com> - 1.7.4-0
- Autogenerated by Bloom

