Name:           ros-lunar-laser-filters
Version:        1.8.5
Release:        0%{?dist}
Summary:        ROS laser_filters package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/laser_filters
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-angles
Requires:       ros-lunar-filters
Requires:       ros-lunar-laser-geometry
Requires:       ros-lunar-message-filters
Requires:       ros-lunar-pluginlib
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-sensor-msgs
Requires:       ros-lunar-tf
BuildRequires:  ros-lunar-angles
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-filters
BuildRequires:  ros-lunar-laser-geometry
BuildRequires:  ros-lunar-message-filters
BuildRequires:  ros-lunar-pluginlib
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-rostest
BuildRequires:  ros-lunar-sensor-msgs
BuildRequires:  ros-lunar-tf

%description
Assorted filters designed to operate on 2D planar laser scanners, which use the
sensor_msgs/LaserScan type.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Wed Sep 06 2017 Jon Binney <jon.binney@gmail.com> - 1.8.5-0
- Autogenerated by Bloom

* Fri Apr 07 2017 Jon Binney <jon.binney@gmail.com> - 1.8.4-1
- Autogenerated by Bloom

* Fri Apr 07 2017 Jon Binney <jon.binney@gmail.com> - 1.8.4-0
- Autogenerated by Bloom

* Mon Apr 03 2017 Jon Binney <jon.binney@gmail.com> - 1.8.3-1
- Autogenerated by Bloom

* Sun Apr 02 2017 Jon Binney <jon.binney@gmail.com> - 1.8.3-0
- Autogenerated by Bloom

