Name:           ros-kinetic-laser-filters
Version:        1.8.5
Release:        0%{?dist}
Summary:        ROS laser_filters package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/laser_filters
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-angles
Requires:       ros-kinetic-filters
Requires:       ros-kinetic-laser-geometry
Requires:       ros-kinetic-message-filters
Requires:       ros-kinetic-pluginlib
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-tf
BuildRequires:  ros-kinetic-angles
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-filters
BuildRequires:  ros-kinetic-laser-geometry
BuildRequires:  ros-kinetic-message-filters
BuildRequires:  ros-kinetic-pluginlib
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-rostest
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-tf

%description
Assorted filters designed to operate on 2D planar laser scanners, which use the
sensor_msgs/LaserScan type.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Sep 06 2017 Jon Binney <jon.binney@gmail.com> - 1.8.5-0
- Autogenerated by Bloom

* Fri May 20 2016 Jon Binney <jon.binney@gmail.com> - 1.8.3-0
- Autogenerated by Bloom

* Wed Apr 06 2016 Jon Binney <jon.binney@gmail.com> - 1.8.2-1
- Autogenerated by Bloom

* Wed Apr 06 2016 Jon Binney <jon.binney@gmail.com> - 1.8.2-0
- Autogenerated by Bloom

